services:
  - type: web
    name: keyrd-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: keyrd_backend
    envVars:
      - key: FLASK_ENV
        value: production
